/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin;

import com.sysma.goat.eclipse_plugin.AbstractGoatInfrastructureRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GoatInfrastructureRuntimeModule extends AbstractGoatInfrastructureRuntimeModule {
}
