/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents.impl;

import com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage;
import com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart;
import com.sysma.goat.eclipse_plugin.goatComponents.Preconditions;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input Processes Part</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.impl.InputProcessesPartImpl#getInputs <em>Inputs</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.impl.InputProcessesPartImpl#getPreconds <em>Preconds</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InputProcessesPartImpl extends MinimalEObjectImpl.Container implements InputProcessesPart
{
  /**
   * The cached value of the '{@link #getInputs() <em>Inputs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputs()
   * @generated
   * @ordered
   */
  protected EList<com.sysma.goat.eclipse_plugin.goatComponents.Process> inputs;

  /**
   * The cached value of the '{@link #getPreconds() <em>Preconds</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreconds()
   * @generated
   * @ordered
   */
  protected EList<Preconditions> preconds;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputProcessesPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoatComponentsPackage.Literals.INPUT_PROCESSES_PART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<com.sysma.goat.eclipse_plugin.goatComponents.Process> getInputs()
  {
    if (inputs == null)
    {
      inputs = new EObjectContainmentEList<com.sysma.goat.eclipse_plugin.goatComponents.Process>(com.sysma.goat.eclipse_plugin.goatComponents.Process.class, this, GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS);
    }
    return inputs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Preconditions> getPreconds()
  {
    if (preconds == null)
    {
      preconds = new EObjectContainmentEList<Preconditions>(Preconditions.class, this, GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS);
    }
    return preconds;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS:
        return ((InternalEList<?>)getInputs()).basicRemove(otherEnd, msgs);
      case GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS:
        return ((InternalEList<?>)getPreconds()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS:
        return getInputs();
      case GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS:
        return getPreconds();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS:
        getInputs().clear();
        getInputs().addAll((Collection<? extends com.sysma.goat.eclipse_plugin.goatComponents.Process>)newValue);
        return;
      case GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS:
        getPreconds().clear();
        getPreconds().addAll((Collection<? extends Preconditions>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS:
        getInputs().clear();
        return;
      case GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS:
        getPreconds().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoatComponentsPackage.INPUT_PROCESSES_PART__INPUTS:
        return inputs != null && !inputs.isEmpty();
      case GoatComponentsPackage.INPUT_PROCESSES_PART__PRECONDS:
        return preconds != null && !preconds.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //InputProcessesPartImpl
