/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents.util;

import com.sysma.goat.eclipse_plugin.goatComponents.And;
import com.sysma.goat.eclipse_plugin.goatComponents.AttributeToSet;
import com.sysma.goat.eclipse_plugin.goatComponents.Awareness;
import com.sysma.goat.eclipse_plugin.goatComponents.BoolConstant;
import com.sysma.goat.eclipse_plugin.goatComponents.CallProcess;
import com.sysma.goat.eclipse_plugin.goatComponents.Comparison;
import com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeRef;
import com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeToSet;
import com.sysma.goat.eclipse_plugin.goatComponents.ComponentDefinition;
import com.sysma.goat.eclipse_plugin.goatComponents.Concatenate;
import com.sysma.goat.eclipse_plugin.goatComponents.Environment;
import com.sysma.goat.eclipse_plugin.goatComponents.Equality;
import com.sysma.goat.eclipse_plugin.goatComponents.Expression;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncBlock;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncDefinition;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncIfElse;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncParam;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncReturn;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncStatement;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncVarAssign;
import com.sysma.goat.eclipse_plugin.goatComponents.FuncVarDeclaration;
import com.sysma.goat.eclipse_plugin.goatComponents.FunctionCall;
import com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage;
import com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess;
import com.sysma.goat.eclipse_plugin.goatComponents.IfProcesses;
import com.sysma.goat.eclipse_plugin.goatComponents.InputProcess;
import com.sysma.goat.eclipse_plugin.goatComponents.InputProcesses;
import com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart;
import com.sysma.goat.eclipse_plugin.goatComponents.IntConstant;
import com.sysma.goat.eclipse_plugin.goatComponents.InterleavingProcess;
import com.sysma.goat.eclipse_plugin.goatComponents.LRef;
import com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeRef;
import com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeToSet;
import com.sysma.goat.eclipse_plugin.goatComponents.LocalVarRef;
import com.sysma.goat.eclipse_plugin.goatComponents.Minus;
import com.sysma.goat.eclipse_plugin.goatComponents.Model;
import com.sysma.goat.eclipse_plugin.goatComponents.MulOrDiv;
import com.sysma.goat.eclipse_plugin.goatComponents.Not;
import com.sysma.goat.eclipse_plugin.goatComponents.Or;
import com.sysma.goat.eclipse_plugin.goatComponents.OutputProcess;
import com.sysma.goat.eclipse_plugin.goatComponents.OutputProcessPart;
import com.sysma.goat.eclipse_plugin.goatComponents.Plus;
import com.sysma.goat.eclipse_plugin.goatComponents.Preconditions;
import com.sysma.goat.eclipse_plugin.goatComponents.PrintAllStatement;
import com.sysma.goat.eclipse_plugin.goatComponents.PrintFormattedStatement;
import com.sysma.goat.eclipse_plugin.goatComponents.PrintStatement;
import com.sysma.goat.eclipse_plugin.goatComponents.ProcessDefinition;
import com.sysma.goat.eclipse_plugin.goatComponents.RecAttributeRef;
import com.sysma.goat.eclipse_plugin.goatComponents.StringConstant;
import com.sysma.goat.eclipse_plugin.goatComponents.Update;
import com.sysma.goat.eclipse_plugin.goatComponents.ZeroProcess;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage
 * @generated
 */
public class GoatComponentsAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static GoatComponentsPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GoatComponentsAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = GoatComponentsPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GoatComponentsSwitch<Adapter> modelSwitch =
    new GoatComponentsSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseProcess(com.sysma.goat.eclipse_plugin.goatComponents.Process object)
      {
        return createProcessAdapter();
      }
      @Override
      public Adapter casePreconditions(Preconditions object)
      {
        return createPreconditionsAdapter();
      }
      @Override
      public Adapter caseInputProcessesPart(InputProcessesPart object)
      {
        return createInputProcessesPartAdapter();
      }
      @Override
      public Adapter caseOutputProcessPart(OutputProcessPart object)
      {
        return createOutputProcessPartAdapter();
      }
      @Override
      public Adapter casePrintStatement(PrintStatement object)
      {
        return createPrintStatementAdapter();
      }
      @Override
      public Adapter casePrintAllStatement(PrintAllStatement object)
      {
        return createPrintAllStatementAdapter();
      }
      @Override
      public Adapter casePrintFormattedStatement(PrintFormattedStatement object)
      {
        return createPrintFormattedStatementAdapter();
      }
      @Override
      public Adapter caseUpdate(Update object)
      {
        return createUpdateAdapter();
      }
      @Override
      public Adapter caseAwareness(Awareness object)
      {
        return createAwarenessAdapter();
      }
      @Override
      public Adapter caseProcessDefinition(ProcessDefinition object)
      {
        return createProcessDefinitionAdapter();
      }
      @Override
      public Adapter caseExpression(Expression object)
      {
        return createExpressionAdapter();
      }
      @Override
      public Adapter caseEnvironment(Environment object)
      {
        return createEnvironmentAdapter();
      }
      @Override
      public Adapter caseComponentDefinition(ComponentDefinition object)
      {
        return createComponentDefinitionAdapter();
      }
      @Override
      public Adapter caseLRef(LRef object)
      {
        return createLRefAdapter();
      }
      @Override
      public Adapter caseAttributeToSet(AttributeToSet object)
      {
        return createAttributeToSetAdapter();
      }
      @Override
      public Adapter caseFuncParam(FuncParam object)
      {
        return createFuncParamAdapter();
      }
      @Override
      public Adapter caseFuncDefinition(FuncDefinition object)
      {
        return createFuncDefinitionAdapter();
      }
      @Override
      public Adapter caseFuncBlock(FuncBlock object)
      {
        return createFuncBlockAdapter();
      }
      @Override
      public Adapter caseFuncStatement(FuncStatement object)
      {
        return createFuncStatementAdapter();
      }
      @Override
      public Adapter caseFuncVarDeclaration(FuncVarDeclaration object)
      {
        return createFuncVarDeclarationAdapter();
      }
      @Override
      public Adapter caseFuncVarAssign(FuncVarAssign object)
      {
        return createFuncVarAssignAdapter();
      }
      @Override
      public Adapter caseFuncIfElse(FuncIfElse object)
      {
        return createFuncIfElseAdapter();
      }
      @Override
      public Adapter caseFuncReturn(FuncReturn object)
      {
        return createFuncReturnAdapter();
      }
      @Override
      public Adapter caseInterleavingProcess(InterleavingProcess object)
      {
        return createInterleavingProcessAdapter();
      }
      @Override
      public Adapter caseOutputProcess(OutputProcess object)
      {
        return createOutputProcessAdapter();
      }
      @Override
      public Adapter caseInputProcesses(InputProcesses object)
      {
        return createInputProcessesAdapter();
      }
      @Override
      public Adapter caseInputProcess(InputProcess object)
      {
        return createInputProcessAdapter();
      }
      @Override
      public Adapter caseIfProcesses(IfProcesses object)
      {
        return createIfProcessesAdapter();
      }
      @Override
      public Adapter caseIfBranchProcess(IfBranchProcess object)
      {
        return createIfBranchProcessAdapter();
      }
      @Override
      public Adapter caseCallProcess(CallProcess object)
      {
        return createCallProcessAdapter();
      }
      @Override
      public Adapter caseZeroProcess(ZeroProcess object)
      {
        return createZeroProcessAdapter();
      }
      @Override
      public Adapter caseIntConstant(IntConstant object)
      {
        return createIntConstantAdapter();
      }
      @Override
      public Adapter caseStringConstant(StringConstant object)
      {
        return createStringConstantAdapter();
      }
      @Override
      public Adapter caseBoolConstant(BoolConstant object)
      {
        return createBoolConstantAdapter();
      }
      @Override
      public Adapter caseOr(Or object)
      {
        return createOrAdapter();
      }
      @Override
      public Adapter caseAnd(And object)
      {
        return createAndAdapter();
      }
      @Override
      public Adapter caseEquality(Equality object)
      {
        return createEqualityAdapter();
      }
      @Override
      public Adapter caseComparison(Comparison object)
      {
        return createComparisonAdapter();
      }
      @Override
      public Adapter casePlus(Plus object)
      {
        return createPlusAdapter();
      }
      @Override
      public Adapter caseMinus(Minus object)
      {
        return createMinusAdapter();
      }
      @Override
      public Adapter caseConcatenate(Concatenate object)
      {
        return createConcatenateAdapter();
      }
      @Override
      public Adapter caseMulOrDiv(MulOrDiv object)
      {
        return createMulOrDivAdapter();
      }
      @Override
      public Adapter caseNot(Not object)
      {
        return createNotAdapter();
      }
      @Override
      public Adapter caseLocalVarRef(LocalVarRef object)
      {
        return createLocalVarRefAdapter();
      }
      @Override
      public Adapter caseLocalAttributeRef(LocalAttributeRef object)
      {
        return createLocalAttributeRefAdapter();
      }
      @Override
      public Adapter caseFunctionCall(FunctionCall object)
      {
        return createFunctionCallAdapter();
      }
      @Override
      public Adapter caseComponentAttributeRef(ComponentAttributeRef object)
      {
        return createComponentAttributeRefAdapter();
      }
      @Override
      public Adapter caseRecAttributeRef(RecAttributeRef object)
      {
        return createRecAttributeRefAdapter();
      }
      @Override
      public Adapter caseComponentAttributeToSet(ComponentAttributeToSet object)
      {
        return createComponentAttributeToSetAdapter();
      }
      @Override
      public Adapter caseLocalAttributeToSet(LocalAttributeToSet object)
      {
        return createLocalAttributeToSetAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Process
   * @generated
   */
  public Adapter createProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Preconditions <em>Preconditions</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Preconditions
   * @generated
   */
  public Adapter createPreconditionsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart <em>Input Processes Part</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart
   * @generated
   */
  public Adapter createInputProcessesPartAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.OutputProcessPart <em>Output Process Part</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.OutputProcessPart
   * @generated
   */
  public Adapter createOutputProcessPartAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.PrintStatement <em>Print Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.PrintStatement
   * @generated
   */
  public Adapter createPrintStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.PrintAllStatement <em>Print All Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.PrintAllStatement
   * @generated
   */
  public Adapter createPrintAllStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.PrintFormattedStatement <em>Print Formatted Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.PrintFormattedStatement
   * @generated
   */
  public Adapter createPrintFormattedStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Update <em>Update</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Update
   * @generated
   */
  public Adapter createUpdateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Awareness <em>Awareness</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Awareness
   * @generated
   */
  public Adapter createAwarenessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessDefinition <em>Process Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.ProcessDefinition
   * @generated
   */
  public Adapter createProcessDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Expression
   * @generated
   */
  public Adapter createExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Environment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Environment
   * @generated
   */
  public Adapter createEnvironmentAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.ComponentDefinition <em>Component Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.ComponentDefinition
   * @generated
   */
  public Adapter createComponentDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.LRef <em>LRef</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.LRef
   * @generated
   */
  public Adapter createLRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.AttributeToSet <em>Attribute To Set</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.AttributeToSet
   * @generated
   */
  public Adapter createAttributeToSetAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncParam <em>Func Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncParam
   * @generated
   */
  public Adapter createFuncParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncDefinition <em>Func Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncDefinition
   * @generated
   */
  public Adapter createFuncDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncBlock <em>Func Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncBlock
   * @generated
   */
  public Adapter createFuncBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncStatement <em>Func Statement</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncStatement
   * @generated
   */
  public Adapter createFuncStatementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncVarDeclaration <em>Func Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncVarDeclaration
   * @generated
   */
  public Adapter createFuncVarDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncVarAssign <em>Func Var Assign</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncVarAssign
   * @generated
   */
  public Adapter createFuncVarAssignAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncIfElse <em>Func If Else</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncIfElse
   * @generated
   */
  public Adapter createFuncIfElseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FuncReturn <em>Func Return</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FuncReturn
   * @generated
   */
  public Adapter createFuncReturnAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.InterleavingProcess <em>Interleaving Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.InterleavingProcess
   * @generated
   */
  public Adapter createInterleavingProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.OutputProcess <em>Output Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.OutputProcess
   * @generated
   */
  public Adapter createOutputProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcesses <em>Input Processes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.InputProcesses
   * @generated
   */
  public Adapter createInputProcessesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcess <em>Input Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.InputProcess
   * @generated
   */
  public Adapter createInputProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.IfProcesses <em>If Processes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.IfProcesses
   * @generated
   */
  public Adapter createIfProcessesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess <em>If Branch Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess
   * @generated
   */
  public Adapter createIfBranchProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.CallProcess <em>Call Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.CallProcess
   * @generated
   */
  public Adapter createCallProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.ZeroProcess <em>Zero Process</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.ZeroProcess
   * @generated
   */
  public Adapter createZeroProcessAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.IntConstant <em>Int Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.IntConstant
   * @generated
   */
  public Adapter createIntConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.StringConstant <em>String Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.StringConstant
   * @generated
   */
  public Adapter createStringConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.BoolConstant
   * @generated
   */
  public Adapter createBoolConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Or
   * @generated
   */
  public Adapter createOrAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.And
   * @generated
   */
  public Adapter createAndAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Equality <em>Equality</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Equality
   * @generated
   */
  public Adapter createEqualityAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Comparison
   * @generated
   */
  public Adapter createComparisonAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Plus
   * @generated
   */
  public Adapter createPlusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Minus
   * @generated
   */
  public Adapter createMinusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Concatenate <em>Concatenate</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Concatenate
   * @generated
   */
  public Adapter createConcatenateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.MulOrDiv <em>Mul Or Div</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.MulOrDiv
   * @generated
   */
  public Adapter createMulOrDivAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.Not
   * @generated
   */
  public Adapter createNotAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.LocalVarRef <em>Local Var Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.LocalVarRef
   * @generated
   */
  public Adapter createLocalVarRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeRef <em>Local Attribute Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeRef
   * @generated
   */
  public Adapter createLocalAttributeRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.FunctionCall
   * @generated
   */
  public Adapter createFunctionCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeRef <em>Component Attribute Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeRef
   * @generated
   */
  public Adapter createComponentAttributeRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.RecAttributeRef <em>Rec Attribute Ref</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.RecAttributeRef
   * @generated
   */
  public Adapter createRecAttributeRefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeToSet <em>Component Attribute To Set</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.ComponentAttributeToSet
   * @generated
   */
  public Adapter createComponentAttributeToSetAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeToSet <em>Local Attribute To Set</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.LocalAttributeToSet
   * @generated
   */
  public Adapter createLocalAttributeToSetAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //GoatComponentsAdapterFactory
