/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.CallProcess#getProcname <em>Procname</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getCallProcess()
 * @model
 * @generated
 */
public interface CallProcess extends com.sysma.goat.eclipse_plugin.goatComponents.Process
{
  /**
   * Returns the value of the '<em><b>Procname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procname</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procname</em>' reference.
   * @see #setProcname(ProcessDefinition)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getCallProcess_Procname()
   * @model
   * @generated
   */
  ProcessDefinition getProcname();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.CallProcess#getProcname <em>Procname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procname</em>' reference.
   * @see #getProcname()
   * @generated
   */
  void setProcname(ProcessDefinition value);

} // CallProcess
