/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Param</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getFuncParam()
 * @model
 * @generated
 */
public interface FuncParam extends FuncVarParam
{
} // FuncParam
