/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Pred</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getFuncPred()
 * @model
 * @generated
 */
public interface FuncPred extends EObject
{
} // FuncPred
