/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage
 * @generated
 */
public interface GoatComponentsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GoatComponentsFactory eINSTANCE = com.sysma.goat.eclipse_plugin.goatComponents.impl.GoatComponentsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Process</em>'.
   * @generated
   */
  Process createProcess();

  /**
   * Returns a new object of class '<em>Preconditions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Preconditions</em>'.
   * @generated
   */
  Preconditions createPreconditions();

  /**
   * Returns a new object of class '<em>Input Processes Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Processes Part</em>'.
   * @generated
   */
  InputProcessesPart createInputProcessesPart();

  /**
   * Returns a new object of class '<em>Output Process Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Process Part</em>'.
   * @generated
   */
  OutputProcessPart createOutputProcessPart();

  /**
   * Returns a new object of class '<em>Update</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Update</em>'.
   * @generated
   */
  Update createUpdate();

  /**
   * Returns a new object of class '<em>Awareness</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Awareness</em>'.
   * @generated
   */
  Awareness createAwareness();

  /**
   * Returns a new object of class '<em>Process Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Process Definition</em>'.
   * @generated
   */
  ProcessDefinition createProcessDefinition();

  /**
   * Returns a new object of class '<em>Environment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Environment</em>'.
   * @generated
   */
  Environment createEnvironment();

  /**
   * Returns a new object of class '<em>Component Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Definition</em>'.
   * @generated
   */
  ComponentDefinition createComponentDefinition();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Rec Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rec Attribute</em>'.
   * @generated
   */
  RecAttribute createRecAttribute();

  /**
   * Returns a new object of class '<em>Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Value</em>'.
   * @generated
   */
  Value createValue();

  /**
   * Returns a new object of class '<em>Pred</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pred</em>'.
   * @generated
   */
  Pred createPred();

  /**
   * Returns a new object of class '<em>Func Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Param</em>'.
   * @generated
   */
  FuncParam createFuncParam();

  /**
   * Returns a new object of class '<em>Func Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Definition</em>'.
   * @generated
   */
  FuncDefinition createFuncDefinition();

  /**
   * Returns a new object of class '<em>Func Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Block</em>'.
   * @generated
   */
  FuncBlock createFuncBlock();

  /**
   * Returns a new object of class '<em>Func Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Statement</em>'.
   * @generated
   */
  FuncStatement createFuncStatement();

  /**
   * Returns a new object of class '<em>Func Var Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Var Declaration</em>'.
   * @generated
   */
  FuncVarDeclaration createFuncVarDeclaration();

  /**
   * Returns a new object of class '<em>Func Var Assign</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Var Assign</em>'.
   * @generated
   */
  FuncVarAssign createFuncVarAssign();

  /**
   * Returns a new object of class '<em>Func Var Param</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Var Param</em>'.
   * @generated
   */
  FuncVarParam createFuncVarParam();

  /**
   * Returns a new object of class '<em>Func Val</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Val</em>'.
   * @generated
   */
  FuncVal createFuncVal();

  /**
   * Returns a new object of class '<em>Func Pred</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Pred</em>'.
   * @generated
   */
  FuncPred createFuncPred();

  /**
   * Returns a new object of class '<em>Func If Else</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func If Else</em>'.
   * @generated
   */
  FuncIfElse createFuncIfElse();

  /**
   * Returns a new object of class '<em>Func Return</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Return</em>'.
   * @generated
   */
  FuncReturn createFuncReturn();

  /**
   * Returns a new object of class '<em>Interleaving Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interleaving Process</em>'.
   * @generated
   */
  InterleavingProcess createInterleavingProcess();

  /**
   * Returns a new object of class '<em>Output Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output Process</em>'.
   * @generated
   */
  OutputProcess createOutputProcess();

  /**
   * Returns a new object of class '<em>Input Processes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Processes</em>'.
   * @generated
   */
  InputProcesses createInputProcesses();

  /**
   * Returns a new object of class '<em>Input Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Process</em>'.
   * @generated
   */
  InputProcess createInputProcess();

  /**
   * Returns a new object of class '<em>If Processes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Processes</em>'.
   * @generated
   */
  IfProcesses createIfProcesses();

  /**
   * Returns a new object of class '<em>If Branch Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>If Branch Process</em>'.
   * @generated
   */
  IfBranchProcess createIfBranchProcess();

  /**
   * Returns a new object of class '<em>Call Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Process</em>'.
   * @generated
   */
  CallProcess createCallProcess();

  /**
   * Returns a new object of class '<em>Zero Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zero Process</em>'.
   * @generated
   */
  ZeroProcess createZeroProcess();

  /**
   * Returns a new object of class '<em>Attribute Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Value</em>'.
   * @generated
   */
  AttributeValue createAttributeValue();

  /**
   * Returns a new object of class '<em>Immediate Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Immediate Value</em>'.
   * @generated
   */
  ImmediateValue createImmediateValue();

  /**
   * Returns a new object of class '<em>Go String Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Go String Function</em>'.
   * @generated
   */
  GoStringFunction createGoStringFunction();

  /**
   * Returns a new object of class '<em>Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Predicate</em>'.
   * @generated
   */
  Predicate createPredicate();

  /**
   * Returns a new object of class '<em>And</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And</em>'.
   * @generated
   */
  And createAnd();

  /**
   * Returns a new object of class '<em>Not</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not</em>'.
   * @generated
   */
  Not createNot();

  /**
   * Returns a new object of class '<em>Immediate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Immediate</em>'.
   * @generated
   */
  Immediate createImmediate();

  /**
   * Returns a new object of class '<em>Equality Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equality Test</em>'.
   * @generated
   */
  EqualityTest createEqualityTest();

  /**
   * Returns a new object of class '<em>Func String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func String</em>'.
   * @generated
   */
  FuncString createFuncString();

  /**
   * Returns a new object of class '<em>Func Memory Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Memory Ref</em>'.
   * @generated
   */
  FuncMemoryRef createFuncMemoryRef();

  /**
   * Returns a new object of class '<em>Func Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Predicate</em>'.
   * @generated
   */
  FuncPredicate createFuncPredicate();

  /**
   * Returns a new object of class '<em>Func And</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func And</em>'.
   * @generated
   */
  FuncAnd createFuncAnd();

  /**
   * Returns a new object of class '<em>Func Not</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Not</em>'.
   * @generated
   */
  FuncNot createFuncNot();

  /**
   * Returns a new object of class '<em>Func Immediate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Immediate</em>'.
   * @generated
   */
  FuncImmediate createFuncImmediate();

  /**
   * Returns a new object of class '<em>Func Equality Test</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Func Equality Test</em>'.
   * @generated
   */
  FuncEqualityTest createFuncEqualityTest();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GoatComponentsPackage getGoatComponentsPackage();

} //GoatComponentsFactory
