/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Branch Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess#getCond <em>Cond</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getIfBranchProcess()
 * @model
 * @generated
 */
public interface IfBranchProcess extends com.sysma.goat.eclipse_plugin.goatComponents.Process
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Preconditions)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getIfBranchProcess_Cond()
   * @model containment="true"
   * @generated
   */
  Preconditions getCond();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Preconditions value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(com.sysma.goat.eclipse_plugin.goatComponents.Process)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getIfBranchProcess_Then()
   * @model containment="true"
   * @generated
   */
  com.sysma.goat.eclipse_plugin.goatComponents.Process getThen();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.IfBranchProcess#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(com.sysma.goat.eclipse_plugin.goatComponents.Process value);

} // IfBranchProcess
