/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Immediate Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.ImmediateValue#getImm <em>Imm</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getImmediateValue()
 * @model
 * @generated
 */
public interface ImmediateValue extends Value
{
  /**
   * Returns the value of the '<em><b>Imm</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imm</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imm</em>' attribute.
   * @see #setImm(String)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getImmediateValue_Imm()
   * @model
   * @generated
   */
  String getImm();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.ImmediateValue#getImm <em>Imm</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imm</em>' attribute.
   * @see #getImm()
   * @generated
   */
  void setImm(String value);

} // ImmediateValue
