/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcess#getRec_pred <em>Rec pred</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcess#getMsgInParts <em>Msg In Parts</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcess()
 * @model
 * @generated
 */
public interface InputProcess extends com.sysma.goat.eclipse_plugin.goatComponents.Process
{
  /**
   * Returns the value of the '<em><b>Rec pred</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec pred</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec pred</em>' containment reference.
   * @see #setRec_pred(Expression)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcess_Rec_pred()
   * @model containment="true"
   * @generated
   */
  Expression getRec_pred();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcess#getRec_pred <em>Rec pred</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rec pred</em>' containment reference.
   * @see #getRec_pred()
   * @generated
   */
  void setRec_pred(Expression value);

  /**
   * Returns the value of the '<em><b>Msg In Parts</b></em>' containment reference list.
   * The list contents are of type {@link com.sysma.goat.eclipse_plugin.goatComponents.AttributeToSet}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Msg In Parts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Msg In Parts</em>' containment reference list.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcess_MsgInParts()
   * @model containment="true"
   * @generated
   */
  EList<AttributeToSet> getMsgInParts();

} // InputProcess
