/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Processes Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart#getInputs <em>Inputs</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.InputProcessesPart#getPreconds <em>Preconds</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcessesPart()
 * @model
 * @generated
 */
public interface InputProcessesPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Inputs</b></em>' containment reference list.
   * The list contents are of type {@link com.sysma.goat.eclipse_plugin.goatComponents.Process}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inputs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inputs</em>' containment reference list.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcessesPart_Inputs()
   * @model containment="true"
   * @generated
   */
  EList<com.sysma.goat.eclipse_plugin.goatComponents.Process> getInputs();

  /**
   * Returns the value of the '<em><b>Preconds</b></em>' containment reference list.
   * The list contents are of type {@link com.sysma.goat.eclipse_plugin.goatComponents.Preconditions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Preconds</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preconds</em>' containment reference list.
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getInputProcessesPart_Preconds()
   * @model containment="true"
   * @generated
   */
  EList<Preconditions> getPreconds();

} // InputProcessesPart
