/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Spawn</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessSpawn#getBlk <em>Blk</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessSpawn()
 * @model
 * @generated
 */
public interface ProcessSpawn extends ProcessStatement
{
  /**
   * Returns the value of the '<em><b>Blk</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Blk</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blk</em>' containment reference.
   * @see #setBlk(PDPBlock)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getProcessSpawn_Blk()
   * @model containment="true"
   * @generated
   */
  PDPBlock getBlk();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.ProcessSpawn#getBlk <em>Blk</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Blk</em>' containment reference.
   * @see #getBlk()
   * @generated
   */
  void setBlk(PDPBlock value);

} // ProcessSpawn
