/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatComponents;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple Get</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.TupleGet#getElem <em>Elem</em>}</li>
 *   <li>{@link com.sysma.goat.eclipse_plugin.goatComponents.TupleGet#getIdx <em>Idx</em>}</li>
 * </ul>
 *
 * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getTupleGet()
 * @model
 * @generated
 */
public interface TupleGet extends Expression
{
  /**
   * Returns the value of the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elem</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elem</em>' containment reference.
   * @see #setElem(Expression)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getTupleGet_Elem()
   * @model containment="true"
   * @generated
   */
  Expression getElem();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.TupleGet#getElem <em>Elem</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elem</em>' containment reference.
   * @see #getElem()
   * @generated
   */
  void setElem(Expression value);

  /**
   * Returns the value of the '<em><b>Idx</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Idx</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Idx</em>' containment reference.
   * @see #setIdx(Expression)
   * @see com.sysma.goat.eclipse_plugin.goatComponents.GoatComponentsPackage#getTupleGet_Idx()
   * @model containment="true"
   * @generated
   */
  Expression getIdx();

  /**
   * Sets the value of the '{@link com.sysma.goat.eclipse_plugin.goatComponents.TupleGet#getIdx <em>Idx</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Idx</em>' containment reference.
   * @see #getIdx()
   * @generated
   */
  void setIdx(Expression value);

} // TupleGet
