/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatInfrastructure;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cluster</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.GoatInfrastructurePackage#getCluster()
 * @model
 * @generated
 */
public interface Cluster extends Params
{
} // Cluster
