/**
 * generated by Xtext 2.12.0
 */
package com.sysma.goat.eclipse_plugin.goatInfrastructure;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.GoatInfrastructureFactory
 * @model kind="package"
 * @generated
 */
public interface GoatInfrastructurePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "goatInfrastructure";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sysma.com/goat/eclipse_plugin/GoatInfrastructure";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "goatInfrastructure";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GoatInfrastructurePackage eINSTANCE = com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl.init();

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.InfrastructureImpl <em>Infrastructure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.InfrastructureImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getInfrastructure()
   * @generated
   */
  int INFRASTRUCTURE = 0;

  /**
   * The number of structural features of the '<em>Infrastructure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFRASTRUCTURE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.SingleServerImpl <em>Single Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.SingleServerImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getSingleServer()
   * @generated
   */
  int SINGLE_SERVER = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_SERVER__PARAMS = INFRASTRUCTURE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_SERVER__NAME = INFRASTRUCTURE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Single Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_SERVER_FEATURE_COUNT = INFRASTRUCTURE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamsImpl <em>Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamsImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getParams()
   * @generated
   */
  int PARAMS = 5;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS__PARAMS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS__NAME = 1;

  /**
   * The number of structural features of the '<em>Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ClusterImpl <em>Cluster</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ClusterImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getCluster()
   * @generated
   */
  int CLUSTER = 2;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__PARAMS = PARAMS__PARAMS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER__NAME = PARAMS__NAME;

  /**
   * The number of structural features of the '<em>Cluster</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLUSTER_FEATURE_COUNT = PARAMS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.RingImpl <em>Ring</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.RingImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getRing()
   * @generated
   */
  int RING = 3;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RING__PARAMS = PARAMS__PARAMS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RING__NAME = PARAMS__NAME;

  /**
   * The number of structural features of the '<em>Ring</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RING_FEATURE_COUNT = PARAMS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.TreeImpl <em>Tree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.TreeImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getTree()
   * @generated
   */
  int TREE = 4;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__PARAMS = PARAMS__PARAMS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__NAME = PARAMS__NAME;

  /**
   * The number of structural features of the '<em>Tree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_FEATURE_COUNT = PARAMS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamImpl
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getParam()
   * @generated
   */
  int PARAM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Infrastructure <em>Infrastructure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Infrastructure</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Infrastructure
   * @generated
   */
  EClass getInfrastructure();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.SingleServer <em>Single Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Server</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.SingleServer
   * @generated
   */
  EClass getSingleServer();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Cluster <em>Cluster</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cluster</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Cluster
   * @generated
   */
  EClass getCluster();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Ring <em>Ring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ring</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Ring
   * @generated
   */
  EClass getRing();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Tree <em>Tree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Tree
   * @generated
   */
  EClass getTree();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Params <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Params</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Params
   * @generated
   */
  EClass getParams();

  /**
   * Returns the meta object for the containment reference list '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Params#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Params#getParams()
   * @see #getParams()
   * @generated
   */
  EReference getParams_Params();

  /**
   * Returns the meta object for the attribute '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Params#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Params#getName()
   * @see #getParams()
   * @generated
   */
  EAttribute getParams_Name();

  /**
   * Returns the meta object for class '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the attribute '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.Param#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.Param#getValue()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GoatInfrastructureFactory getGoatInfrastructureFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.InfrastructureImpl <em>Infrastructure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.InfrastructureImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getInfrastructure()
     * @generated
     */
    EClass INFRASTRUCTURE = eINSTANCE.getInfrastructure();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.SingleServerImpl <em>Single Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.SingleServerImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getSingleServer()
     * @generated
     */
    EClass SINGLE_SERVER = eINSTANCE.getSingleServer();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ClusterImpl <em>Cluster</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ClusterImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getCluster()
     * @generated
     */
    EClass CLUSTER = eINSTANCE.getCluster();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.RingImpl <em>Ring</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.RingImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getRing()
     * @generated
     */
    EClass RING = eINSTANCE.getRing();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.TreeImpl <em>Tree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.TreeImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getTree()
     * @generated
     */
    EClass TREE = eINSTANCE.getTree();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamsImpl <em>Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamsImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getParams()
     * @generated
     */
    EClass PARAMS = eINSTANCE.getParams();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMS__PARAMS = eINSTANCE.getParams_Params();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMS__NAME = eINSTANCE.getParams_Name();

    /**
     * The meta object literal for the '{@link com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.ParamImpl
     * @see com.sysma.goat.eclipse_plugin.goatInfrastructure.impl.GoatInfrastructurePackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__VALUE = eINSTANCE.getParam_Value();

  }

} //GoatInfrastructurePackage
